version: '3'

services:
  db:
    container_name: peche_postgres
    image: postgres:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - ylab_project


  redis:
    container_name: peche_redis
    image: redis:latest
    env_file:
      - ./.env
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ylab_project

  fastapi:
    container_name: peche_fastapi
    build:
      context: .
    command: uvicorn application.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - ylab_project
    restart: always
    depends_on:
      - db
      - redis


networks:
  ylab_project:
    driver: bridge
