"""Add sent_at and received_at columns to messages

Revision ID: 848c31e02f7e
Revises: 46e69168ad42
Create Date: 2024-04-28 20:23:47.252069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848c31e02f7e'
down_revision: Union[str, None] = '46e69168ad42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('messages', sa.Column('received_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'received_at')
    op.drop_column('messages', 'sent_at')
    # ### end Alembic commands ###
