"""logs

Revision ID: c6e58e4c7499
Revises: 491fc72a3816
Create Date: 2024-04-29 17:50:23.750006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e58e4c7499'
down_revision: Union[str, None] = '491fc72a3816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log_journal',
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('request', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_log_journal')
    # ### end Alembic commands ###
