"""set default value to gpa

Revision ID: 23ac45e674e5
Revises: 943449abd8eb
Create Date: 2024-03-13 07:18:39.432067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ac45e674e5'
down_revision: Union[str, None] = '943449abd8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gpa', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gpa')
    # ### end Alembic commands ###
