"""NEW actor relationship fixed

Revision ID: 26e45d4c8edc
Revises: d2f18f099246
Create Date: 2024-03-13 13:12:52.703939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e45d4c8edc'
down_revision: Union[str, None] = 'd2f18f099246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_actor', sa.Column('movies_id', sa.Integer(), nullable=True))
    op.add_column('movie_actor', sa.Column('actors_id', sa.Integer(), nullable=True))
    op.drop_constraint('movie_actor_movie_id_fkey', 'movie_actor', type_='foreignkey')
    op.drop_constraint('movie_actor_actor_id_fkey', 'movie_actor', type_='foreignkey')
    op.create_foreign_key(None, 'movie_actor', 'movies', ['movies_id'], ['id'])
    op.create_foreign_key(None, 'movie_actor', 'actors', ['actors_id'], ['id'])
    op.drop_column('movie_actor', 'actor_id')
    op.drop_column('movie_actor', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_actor', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('movie_actor', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movie_actor', type_='foreignkey')
    op.drop_constraint(None, 'movie_actor', type_='foreignkey')
    op.create_foreign_key('movie_actor_actor_id_fkey', 'movie_actor', 'actors', ['actor_id'], ['id'])
    op.create_foreign_key('movie_actor_movie_id_fkey', 'movie_actor', 'movies', ['movie_id'], ['id'])
    op.drop_column('movie_actor', 'actors_id')
    op.drop_column('movie_actor', 'movies_id')
    # ### end Alembic commands ###
