"""fixed

Revision ID: 9634efbe9b93
Revises: 041fc816a76a
Create Date: 2024-03-13 10:30:53.808695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9634efbe9b93'
down_revision: Union[str, None] = '041fc816a76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('studio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'movies', 'studios', ['studio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'studio_id')
    # ### end Alembic commands ###
