"""inital_migration

Revision ID: 0a1c7dcb9c44
Revises: 57297a071dfc
Create Date: 2024-03-14 22:30:53.471036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1c7dcb9c44'
down_revision: Union[str, None] = '57297a071dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_book_id_fkey', 'authors', type_='foreignkey')
    op.drop_column('authors', 'book_id')
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.add_column('authors', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('authors_book_id_fkey', 'authors', 'authors', ['book_id'], ['id'])
    # ### end Alembic commands ###
