"""another fix movie

Revision ID: 206bd96aa094
Revises: c299d0eb9350
Create Date: 2024-03-02 17:47:46.628284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '206bd96aa094'
down_revision: Union[str, None] = 'c299d0eb9350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('description', sa.String(), nullable=False))
    op.add_column('movies', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'duration')
    op.drop_column('movies', 'rating')
    op.drop_column('movies', 'description')
    # ### end Alembic commands ###
