"""Add created_at column to categories table

Revision ID: f76c3f7c8d20
Revises: 0395c07319e3
Create Date: 2024-03-01 21:17:33.212399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76c3f7c8d20'
down_revision: Union[str, None] = '0395c07319e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_at', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'created_at')
    # ### end Alembic commands ###
