/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kafka.consumer

import org.apache.kafka.clients.consumer.ConsumerConfig
import org.apache.kafka.clients.consumer.KafkaConsumer
import java.time.Duration
import java.util.*

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val properties = Properties().apply {
        put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092")
        put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer")
        put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringDeserializer")
    }

    val consumer = KafkaConsumer<String, String>(properties)

    consumer.subscribe(listOf("currency")) // Poll for new messages
    while (true) {
        val records = consumer.poll(Duration.ofMillis(100))
        for (record in records) {
            println("Received message: ${record.key()} - ${record.value()}")
        }
    }
}
