version: '3.8'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: iguser
      POSTGRES_PASSWORD: igpass
      POSTGRES_DB: targetdb
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
