version: '3.8'

services:
  app:
    build: .
    command: /start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data: