version: "3"

services:  
  auth_service:
    build:
      context: ./AuthenticationService
    restart: on-failure
    container_name: delivery-service-auth_service
    ports:
      - 8000:8000
  
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Dimash2003
      - POSTGRES_USER=postgres
      - POSTGRES_DB=delivery_service

volumes:
  pg_data: { }