import enum


class RequestEnum(enum.Enum):
    ADD_DIRECTOR = "ADD_DIRECTOR"
    DELETE_DIRECTOR = "DELETE_DIRECTOR"

    ADD_MOVIE = "ADD_MOVIE"
    DELETE_MOVIE = "DELETE_MOVIE"

    ADD_MOVIE_GENRE = "ADD_MOVIE_GENRE"
    DELETE_MOVIE_GENRE = "DELETE_MOVIE_GENRE"

    ADD_ACTOR = "ADD_ACTOR"
    DELETE_ACTOR = "DELETE_ACTOR"
