"""sqlalchemy util

Revision ID: d8eb943f2d71
Revises: 926ea6df9a83
Create Date: 2024-05-03 12:41:50.202842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8eb943f2d71'
down_revision: Union[str, None] = '926ea6df9a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('couriers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('couriers', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
