version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: caruser
      POSTGRES_PASSWORD: carpass
      POSTGRES_DB: cardb
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
