"""Initial

Revision ID: 3add07fb8b8a
Revises: d91df05b4fb7
Create Date: 2024-03-12 13:42:12.438083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3add07fb8b8a'
down_revision: Union[str, None] = 'd91df05b4fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'resume_id')
    # ### end Alembic commands ###
