"""fix one to one relationship user and favorite

Revision ID: 4ac551e4c5d9
Revises: a84e8d845680
Create Date: 2024-03-12 11:12:23.987938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac551e4c5d9'
down_revision: Union[str, None] = 'a84e8d845680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
