"""mark bug

Revision ID: f3711a58dc3a
Revises: 4363ff20de87
Create Date: 2024-03-09 16:41:08.300039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3711a58dc3a'
down_revision: Union[str, None] = '4363ff20de87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('mark_id', sa.Integer(), nullable=False))
    op.drop_constraint('vehicles_mark_fkey', 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'marks', ['mark_id'], ['id'])
    op.drop_column('vehicles', 'mark')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('mark', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key('vehicles_mark_fkey', 'vehicles', 'marks', ['mark'], ['id'])
    op.drop_column('vehicles', 'mark_id')
    # ### end Alembic commands ###
