"""set connection between models

Revision ID: f6a56e075039
Revises: 4d98802236d0
Create Date: 2024-03-15 23:21:20.853503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a56e075039'
down_revision: Union[str, None] = '4d98802236d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['client_id'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'client_id')
    # ### end Alembic commands ###
