"""new migration

Revision ID: 5c4776100fbe
Revises: 69647c13a2d3
Create Date: 2024-03-02 16:14:13.613679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4776100fbe'
down_revision: Union[str, None] = '69647c13a2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('name', sa.String(), nullable=False))
    op.add_column('genres', sa.Column('name', sa.String(), nullable=False))
    op.add_column('movies', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'name')
    op.drop_column('genres', 'name')
    op.drop_column('directors', 'name')
    # ### end Alembic commands ###
