"""update defaults

Revision ID: 1af7c08c70b0
Revises: 8691a5a5679d
Create Date: 2024-04-28 01:24:06.563178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af7c08c70b0'
down_revision: Union[str, None] = '8691a5a5679d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('current_speed', sa.Integer(), nullable=False))
    op.add_column('roads', sa.Column('traffic_rate', sa.Float(), nullable=False))
    op.add_column('roads', sa.Column('max_speed', sa.Integer(), nullable=False))
    op.add_column('roads', sa.Column('average_speed', sa.Integer(), nullable=False))
    op.add_column('roads', sa.Column('max_num_of_cars', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roads', 'max_num_of_cars')
    op.drop_column('roads', 'average_speed')
    op.drop_column('roads', 'max_speed')
    op.drop_column('roads', 'traffic_rate')
    op.drop_column('people', 'current_speed')
    # ### end Alembic commands ###
