"""update

Revision ID: 653041893f79
Revises: ffd758044109
Create Date: 2024-04-27 23:48:08.325527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653041893f79'
down_revision: Union[str, None] = 'ffd758044109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_history',
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road_id', sa.Integer(), nullable=False),
    sa.Column('average_speed', sa.Integer(), nullable=False),
    sa.Column('traffic_rate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['roads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('history', sa.Column('timestamps', sa.DateTime(), nullable=True))
    op.drop_column('history', 'timestamp')
    op.add_column('people', sa.Column('current_location_id', sa.Integer(), nullable=False))
    op.add_column('people', sa.Column('current_road_id', sa.Integer(), nullable=False))
    op.drop_constraint('people_current_location_fkey', 'people', type_='foreignkey')
    op.create_foreign_key(None, 'people', 'roads', ['current_road_id'], ['id'])
    op.create_foreign_key(None, 'people', 'locations', ['current_location_id'], ['id'])
    op.drop_column('people', 'current_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('current_location', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.create_foreign_key('people_current_location_fkey', 'people', 'locations', ['current_location'], ['id'])
    op.drop_column('people', 'current_road_id')
    op.drop_column('people', 'current_location_id')
    op.add_column('history', sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('history', 'timestamps')
    op.drop_table('traffic_history')
    # ### end Alembic commands ###
