"""autoincrement

Revision ID: 926ffc6bab6d
Revises: f1c459d2b37e
Create Date: 2024-04-29 16:35:33.292209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926ffc6bab6d'
down_revision: Union[str, None] = 'f1c459d2b37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
