"""login jwt

Revision ID: f1c459d2b37e
Revises: e0d6928cbda0
Create Date: 2024-04-29 16:06:42.422592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c459d2b37e'
down_revision: Union[str, None] = 'e0d6928cbda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('login', sa.String(), nullable=False))
    op.add_column('people', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'people', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'password')
    op.drop_column('people', 'login')
    # ### end Alembic commands ###
