"""changing post models

Revision ID: 1ce8d6499fb4
Revises: 0fcd8e4ab998
Create Date: 2024-03-01 20:13:47.556959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce8d6499fb4'
down_revision: Union[str, None] = '0fcd8e4ab998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
