"""first

Revision ID: 94e7e2b7e32b
Revises: 
Create Date: 2024-03-01 21:03:15.584380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e7e2b7e32b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Human',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birth_day', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['Human.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['Human.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('House',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['Human.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('House')
    op.drop_table('Dog')
    op.drop_table('Cat')
    op.drop_table('Human')
    # ### end Alembic commands ###
