"""test5

Revision ID: 40ed280c440f
Revises: e22176979967
Create Date: 2024-05-10 01:09:29.608528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ed280c440f'
down_revision: Union[str, None] = 'e22176979967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('availability_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'availabilities', ['availability_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'availability_id')
    # ### end Alembic commands ###
