"""test3

Revision ID: 5ab688caa973
Revises: 9a9f9c4eb8d5
Create Date: 2024-05-10 00:51:55.856087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab688caa973'
down_revision: Union[str, None] = '9a9f9c4eb8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('day_of_month', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('hour', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'hour')
    op.drop_column('appointments', 'month')
    op.drop_column('appointments', 'day_of_month')
    # ### end Alembic commands ###
