"""commit-3

Revision ID: 71c508662d13
Revises: 34d065641b9f
Create Date: 2024-05-07 19:26:54.240313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c508662d13'
down_revision: Union[str, None] = '34d065641b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.add_column('users', sa.Column('contribution_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'contributions', ['contribution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contribution_id')
    op.drop_table('contributions')
    # ### end Alembic commands ###
