"""added default value = None

Revision ID: 7ef7ced42ed9
Revises: d53e3b32d84a
Create Date: 2024-05-07 21:03:27.473875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef7ced42ed9'
down_revision: Union[str, None] = 'd53e3b32d84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contribution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contribution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
