"""empty message

Revision ID: 967dab15103a
Revises: 41017db6ff11
Create Date: 2024-05-09 18:10:38.191653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967dab15103a'
down_revision: Union[str, None] = '41017db6ff11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('camera_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'cameras', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'camera_id')
    # ### end Alembic commands ###
