"""upd

Revision ID: 9e0d39f9bf1a
Revises: dc81a91fda12
Create Date: 2024-05-09 21:30:05.724716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0d39f9bf1a'
down_revision: Union[str, None] = 'dc81a91fda12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medical_records', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_column('medical_records', 'patient_id')
    # ### end Alembic commands ###
