"""paymentChange

Revision ID: d99ebe7d55e9
Revises: debc44a64685
Create Date: 2024-05-10 02:35:59.133625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99ebe7d55e9'
down_revision: Union[str, None] = 'debc44a64685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_type', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'payment_type')
    # ### end Alembic commands ###
