"""heartbeat

Revision ID: e09fff6ab14f
Revises: 40ed280c440f
Create Date: 2024-05-10 16:00:45.693561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09fff6ab14f'
down_revision: Union[str, None] = '40ed280c440f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeat_id'), 'heartbeat', ['id'], unique=False)
    op.create_index(op.f('ix_heartbeat_user_id'), 'heartbeat', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeat_user_id'), table_name='heartbeat')
    op.drop_index(op.f('ix_heartbeat_id'), table_name='heartbeat')
    op.drop_table('heartbeat')
    # ### end Alembic commands ###
