"""journal add column request

Revision ID: f4c055c84122
Revises: e0124aa772ee
Create Date: 2024-04-26 14:28:51.127494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c055c84122'
down_revision: Union[str, None] = 'e0124aa772ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('request', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_logs', 'request')
    # ### end Alembic commands ###
