"""second

Revision ID: 4080d5502e16
Revises: fab51cfcf6e8
Create Date: 2024-03-02 17:39:35.599958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4080d5502e16'
down_revision: Union[str, None] = 'fab51cfcf6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('description', sa.Integer(), nullable=False))
    op.add_column('films', sa.Column('rating', sa.Float(), nullable=False))
    op.add_column('films', sa.Column('duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'duration')
    op.drop_column('films', 'rating')
    op.drop_column('films', 'description')
    # ### end Alembic commands ###
