"""initial2

Revision ID: 254b84851728
Revises: cd372c38dbcb
Create Date: 2024-03-01 21:15:38.353395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254b84851728'
down_revision: Union[str, None] = 'cd372c38dbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'citizens', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citizens', type_='foreignkey')
    op.drop_column('citizens', 'country_id')
    # ### end Alembic commands ###
