"""added country-president relation

Revision ID: d0a86d368a49
Revises: 1df888404543
Create Date: 2024-02-24 16:23:55.079280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a86d368a49'
down_revision: Union[str, None] = '1df888404543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presidents', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'presidents', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'presidents', type_='foreignkey')
    op.drop_column('presidents', 'country_id')
    # ### end Alembic commands ###
