"""test 123

Revision ID: c30fb6e43f6b
Revises: 7f44eb44b7c5
Create Date: 2024-03-16 16:53:35.492828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30fb6e43f6b'
down_revision: Union[str, None] = '7f44eb44b7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['coffee_shop_owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('coffee_shop_id', sa.Integer(), nullable=True),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['coffee_shop_id'], ['coffee_shops.id'], )
    )
    op.drop_table('coffe_shops')
    op.alter_column('coffee_shop_owners', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('coffees', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('coffees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('coffees', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coffees', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coffees', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('coffees', 'description')
    op.alter_column('coffee_shop_owners', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('coffe_shops',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='coffe_shops_pkey')
    )
    op.drop_table('association')
    op.drop_table('coffee_shops')
    # ### end Alembic commands ###
